### ISSUE TITLE
Should BLEProcess and BLEApp run dispatch_forever()?

### ISSUE THREAD

**Issue by ghost** [ARMmbed/mbed-os-ble-utils#6]
I'd prefer if an `EventQueue` I created was only truly executed in the code I control.

`BLEProcess` has signfiicantly simplified some of the code I previously had, but I had to comment out the call to `dispatch_forever()` in `start()` in my local copy so I could execute it when I needed it.

**Comment by paul-szczepanek-arm** [comment]
Yes, this is something that I would've done differently and will do differently if I get to write the production version of BLEApp. These utils here are not production code - it's just code do simplify the mbed ble examples, so they can be simpler to concentrate on showing only the features that are the focus of each example.
