### ISSUE TITLE
Allow more custimozation of the advertising payload

### ISSUE THREAD

**Issue by ghost** [ARMmbed/mbed-os-ble-utils#7]
Some missing features:
  
 * appearance
 * intervals
 * service data
 * manufacturer data
 * scan response

 Appearance and intervals seem both obvious and easy. It's possible that the others should be in some sort of callback.
I'm not sure what's best to do here though.

**Comment by ghost** [comment]
I personally need to use manufacturer data, so I just reimplemented `start_advertising` myself.

**Comment by pan-** [comment]
Thanks @jrobeson , We have a discussion open on a Bluetooth application framework: https://github.com/ARMmbed/mbed-os-experimental-ble-services/discussions/25 .

That would be great if you could contribute your thoughts.
